- name: Upload artifact
  uses: actions/upload-pages-artifact@v3
  with:
    path: './dist'
    name: 'vue-sneakers-dist'

- name: Deploy to GitHub Pages
  id: deployment
  uses: actions/deploy-pages@v4
  with:
    artifact_name: 'vue-sneakers-dist'